python add_main_function.py data/all/all_homer_up_goanalysis_concat.txt
python add_main_function.py data/all/all_homer_down_goanalysis_concat.txt

python add_main_function.py data/common/common_homer_up_goanalysis_concat.txt
python add_main_function.py data/common/common_homer_down_goanalysis_concat.txt

python add_main_function.py data/unique/unique_homer_up_goanalysis_concat.txt
python add_main_function.py data/unique/unique_homer_down_goanalysis_concat.txt
